---
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8011/eureka/,http://eureka-tertiary:8012/eureka/,http://eureka-primary:8010/eureka/
  instance:
      instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
word-config:
  lucky-man:  Yuvan
  unlucky-man:  hello
---
spring:
  profiles: lab-4-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: lab-4-subject
words: I,You,He,She,It

---
spring:
  profiles: lab-4-noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profiles: lab-4-article
words: a,the

---
spring:
  profiles: lab-4-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: cold-noun
words: anup,amit,ajay,gopal

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

 
